server:
  port: 8765
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
spring:
  cloud:
    gateway:
      routes:
      - id: dracards-user
        uri:
          lb://dracards-user
        predicates:
        - Path=/api/user/**
  security:
    oauth2:
      client:
        provider:
          keycloak-provider:
            issuer-uri: http://35.231.41.35:8080/auth/realms/drac-realm
        registration:
          keycloak-spring-gateway-client:
               provider: keycloak-provider
               client-id: drac-back-client
               client-secret: 35e9d010-7ecd-404d-bd73-a42b0726a2d9
               authorization-grant-type: authorization_code
               redirect-uri: "{baseUrl}/login/oauth2/code/drac-back-client" 