server:
  port: 8765
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
spring:
  cloud:
    gateway:
      routes:
      - id: dracards-user
        uri:
          lb://dracards-user
        predicates:
        - Path=/api/user/**
  security:
    oauth2:
      client:
        provider:
          keycloak-provider:
            issuer-uri: http://localhost:8080/auth/realms/dracards-realm
        registration:
          keycloak-spring-gateway-client:
               provider: keycloak-provider
               client-id: dracards-api-gateway-client
               client-secret: 1e5c1d8b-de0b-446b-9c48-aa9c08cc9c45
               authorization-grant-type: authorization_code
               redirect-uri: "{baseUrl}/login/oauth2/code/dracards-api-gateway-client" 