eureka:
  client:
    service-url:
      defaultZone: http://35.231.41.35:8761/eureka
spring:
  jackson:
    deserialization:
      fail-on-unknown-properties: false
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
blockfrost:
  ipfs:
    url: https://ipfs.blockfrost.io/api/v0/
    project-id: fbpGi7HSJJGFMz5vlytEcR1H6mIMO6Td
  network:
    project-id: meUhg4EyzJThaa1PFgQY3rvwKlGfCBFe
    url: https://cardano-testnet.blockfrost.io/api/v0/  