eureka:
  client:
    service-url:
      defaultZone: http://35.231.41.35:8761/eureka
spring:
  jackson:
    deserialization:
      fail-on-unknown-properties: false
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false